default: &default
  adapter: solid_cable
  polling_interval: 1.second
  keep_messages_around_for: 1.day

development:
  <<: *default
  silence_polling: true
  connects_to:
    database:
      writing: cable
      reading: cable

test:
  adapter: test

production:
  <<: *default
  polling_interval: 0.1.seconds
