# DEFAULT CONNECTION CONFIGURATION
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# DATABASE CONFIGURATIONS
primary: &primary
  <<: *default
  database: db/<%= Rails.env %>.sqlite3

queue: &queue
  <<: *default
  database: db/<%= Rails.env %>-queue.sqlite3
  migrations_paths: db/queue_migrate

cache: &cache
  <<: *default
  database: db/<%= Rails.env %>-cache.sqlite3

cable: &cable
  <<: *default
  migrations_paths: db/cable_migrate
  database: db/<%= Rails.env %>-cable.sqlite3


# ENVIRONMENT CONFIGURATIONS
development:
  primary: *primary
  queue: *queue
  cache: *cache
  cable: *cable

test:
  primary: *primary
  queue: *queue
  cache: *cache
  cable: *cable

production:
  primary:
    <<: *default
    database: /data/production.sqlite3
  queue:
    <<: *default
    database: /data/production-queue.sqlite3
  cache:
    <<: *default
    database: /data/production-cache.sqlite3
  cable:
    <<: *default
    database: /data/production-cable.sqlite3
