# DEFAULT CONNECTION CONFIGURATION
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# DATABASE CONFIGURATIONS
primary: &primary
  <<: *default
  database: storage/<%= Rails.env %>.sqlite3

queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate
  database: storage/<%= Rails.env %>-queue.sqlite3

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
  database: storage/<%= Rails.env %>-cache.sqlite3

cable: &cable
  <<: *default
  migrations_paths: db/cable_migrate
  database: storage/<%= Rails.env %>-cable.sqlite3  


# ENVIRONMENT CONFIGURATIONS
development:
  primary: *primary
  queue: *queue
  cache: *cache
  cable: *cable

test:
  primary: *primary
  queue: *queue
  cache: *cache
  cable: *cable

production:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    database: <%= ENV['DATABASE_QUEUE_URL'] %>
  cache:
    <<: *default
    database: <%= ENV['DATABASE_CACHE_URL'] %>
  cable:
    <<: *default
    database: <%= ENV['DATABASE_CABLE_URL'] %>