# DEFAULT CONNECTION CONFIGURATION
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# DATABASE CONFIGURATIONS
primary: &primary
  <<: *default
  database: storage/<%= Rails.env %>.sqlite3

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
  database: storage/<%= Rails.env %>-cache.sqlite3

cable: &cable
  <<: *default
  migrations_paths: db/cable_migrate
  database: storage/<%= Rails.env %>-cable.sqlite3  


# ENVIRONMENT CONFIGURATIONS
development:
  primary: *primary
  cache: *cache
  cable: *cable

test:
  primary: *primary
  cache: *cache
  cable: *cable

production:
  primary:
    <<: *default
    database: /data/production.sqlite3  
  cache:
    <<: *default
    database: /data/production-cache.sqlite3  
  cable:
    <<: *default
    database: /data/production-cable.sqlite3  